/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DataBrowser: typeof import('./src/components/DataBrowser.vue')['default']
    DatasetSelector: typeof import('./src/components/DatasetSelector.vue')['default']
    FinancialDataComparison: typeof import('./src/components/FinancialDataComparison.vue')['default']
    FinancialDataDisplay: typeof import('./src/components/FinancialDataDisplay.vue')['default']
    FinancialDataScalingSelector: typeof import('./src/components/FinancialDataScalingSelector.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
