/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComparisonControls: typeof import('./src/components/ComparisonControls.vue')['default']
    ComparisonTooltip: typeof import('./src/components/ComparisonTooltip.vue')['default']
    DataBrowser: typeof import('./src/components/DataBrowser.vue')['default']
    DatasetSelector: typeof import('./src/components/DatasetSelector.vue')['default']
    FinancialDataComparison: typeof import('./src/components/FinancialDataComparison.vue')['default']
    FinancialDataDisplay: typeof import('./src/components/FinancialDataDisplay.vue')['default']
    FinancialDataScalingSelector: typeof import('./src/components/FinancialDataScalingSelector.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}
